name: Test

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        shell: bash
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.x
      - uses: actions/checkout@v4
        with:
          path: 'ipfs-check'
      - name: Tests
        working-directory: ipfs-check
        run: |
          go test ./...